WIP - Columns
hlxsites/nokia pull request #31
Opened 2023-05-04 11:05 UTC by rhudea

Arrange content on grid.
Allow grid split override via section metadata

Fix #15

Test URLs:
- Before: https://main--nokia--hlxsites.hlx.page/drafts/rhudea/7750-service-router
- After: https://15-columns--nokia--hlxsites.hlx.page/drafts/rhudea/7750-service-router

2023-05-05 07:37 UTC, ekremney commented on blocks/reference/reference.css
> +:root {
Please leave the `reference` component out of this PR

2023-05-05 07:37 UTC, ekremney commented on scripts/scripts.js
> +function createGridColumn(style) {
the word `grid` implies a 2-dimensional structure where there are rows and columns. We are only planning to provide columns. So I would rather use the word columns instead of grid for clarity

2023-05-05 07:37 UTC, ekremney commented on scripts/scripts.js
> +    const columnStyle = `nc-${12 / section.children.length}`;
In their current authoring UI, they are not using the term `nc`, it only exists in the page structure which is some technical lingo. To keep it understandable for the non-technical authors, we should use more straightforward terminology such as:

- cols-8-4
- columns-8-4
- columns-75-25
- columns-66-33

<img width="324" alt="Screen Shot 2023-05-05 at 09 18 47" src="https://user-images.githubusercontent.com/1171225/236398190-e020c48a-7c91-4094-901e-eaa9f7142e40.png">

2023-05-05 07:37 UTC, ekremney commented on scripts/scripts.js
> +  const gridType = (section.getAttribute('data-grid') || '8-4').split('-');
Please put the columns type in the style row of section metadata unless there is a strict requirement.

for example:

```
| Section Metadata                |
|-------------------|-------------|
| Style             | column-type |
```

which then be translated to:

```
<div class="section column-type"> ... </div>
```

2023-05-05 07:37 UTC, ekremney commented on scripts/scripts.js
> +    .querySelectorAll('div.section:not(.hero-container)')
not all sections are going to have columnar structure unless they have columns selector in the section metadata. By default, there is no columnar structure and blocks will handle the columns within themselves. For example, only 3 sections will be columnized in the [7750 Service Router page](https://www.nokia.com/networks/ip-networks/7750-service-router/):

- The section comes after hero block (the one with toc)
- The section starts with "Service router applications and network functions"
- The section starts with "Resources"

all other blocks will not be columnized and will span to 100% to the page

2023-05-05 07:37 UTC, ekremney commented on scripts/scripts.js
> +function createToc(main) {
Please keep TOC block out of this PR

2023-05-05 19:03 UTC, ekremney requested changes
Nokia.com is single column when page width is smaller 768px. Please keep that.

2023-05-05 19:03 UTC, ekremney commented on scripts/scripts.js
> +  multiColumnEl.append(leftColumnEl, rightColumnEl);
there's a lot of DOM queries based on the default Franklin DOM structure (`div.section > div.wrapper > div.block`) assuming that the structure will be kept throughout the project. Since this PR is altering the DOM structure, please make sure that any other functionality built with that assumption still works.

example: https://github.com/hlxsites/nokia/blob/main/scripts/lib-franklin.js#L348

2023-05-06 09:32 UTC, ekremney commented
One other missing thing is that autoblocking of the right blocks' headings. If the previous element of the right block is a type of heading, then it should be moved to right columns as well. 

following content

```
h2 - aaa
p

h2 - bbb
block

h2 - ccc
block (right)
```

should look like:

```
+--------------------------+
| h2 - aaa  | h2 - ccc     |
| p         | block (right)|
|           |              |
| h2 - bbb  |              |
| block     |              |
+--------------------------+

2023-05-08 07:40 UTC, rhudea commented
> One other missing thing is that autoblocking of the right blocks' headings. If the previous element of the right block is a type of heading, then it should be moved to right columns as well.
> 
> following content
> 
> ```
> h2 - aaa
> p
> 
> h2 - bbb
> block
> 
> h2 - ccc
> block (right)
> ```
> 
> should look like:
> 
> ```
> +--------------------------+
> | h2 - aaa  | h2 - ccc     |
> | p         | block (right)|
> |           |              |
> | h2 - bbb  |              |
> | block     |              |
> +--------------------------+
> ```

This was explicitly left out to be done as as separate PR once the approach is agreed upon (also mentioned it on the PR description).

2023-05-08 10:16 UTC, rhudea commented on scripts/scripts.js
> +  multiColumnEl.append(leftColumnEl, rightColumnEl);
The columns are configured after the blocks and sections are decorated.
The CSS related to blocks should style only that block (this is the case for existing blocks). The change done by the putting them in columns do not interfere with how blocks are created/updated inside the corresponding block js.
The standard block structure is `block-wrapper > block` and styling is done on `block`.
The columnar layout will create the following structure `two-columns > div > block-wrapper  > block`, which should not interfere with the block structure and style.

The goal is to be able to put a block in either column and that should work by default.

2023-05-08 11:22 UTC, ekremney commented
when width < 768px, column width should be 100%

![Screen Shot 2023-05-08 at 13 22 11](https://user-images.githubusercontent.com/1171225/236811425-dae40398-aeba-47df-b086-90f65c771f57.png)

2023-05-08 18:17 UTC, ekremney approved these changes

2023-05-09 05:57 UTC, merged